---
title: Nonparametric Workshop
date: 08/14/23
date-format: full
subtitle: University of Pretoria
author: Jeffrey S. Racine
institute: McMaster University
format:
  revealjs:
    background-transition: fade
    center: true
    chalkboard: true
    css: custom.css
    embed-resources: false
    footer: "Workshop | J. Racine"
    ## This "hack" is exclusive to using mathjax and allows for plain vanilla
    ## equation cross referencing using any LaTeX math environment such as
    ## align, equation, split, etc., i.e., \label{eqfoo} and \eqref{eqfoo} (it
    ## can also be used for revealjs, html, while standard pdf will naturally
    ## accept it using defaults - breaks if used for docx, ppt etc.)
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>    
    incremental: true
    link-external-newwindow: true
    ## multiplex: true will create two html files:
    ## 1. index.html: This is the file you should publish online and that your
    ## audience should view.
    ## 2. index-speaker.html: This is the file that you should present from.
    ## This file can remain on your computer and does not need to be published
    ## elsewhere.
    multiplex: true
    preview-links: auto
    ## https://github.com/shafayetShafee/reveal-header
    ## quarto add shafayetShafee/reveal-header 
    # sc-sb-title: false
    self-contained-math: true
    show-notes: false
    slide-number: true
    theme: default
    touch: true
    transition: slide
    spotlight:
      size: 180
      lockPointerInsideCanvas: true
revealjs-plugins:
#  - spotlight
editor: source
bibliography: slides.bib
link-citations: true
knitr:
  opts_chunk:
    autodep: true
    collapse: true
    cache: true
    echo: false
    eval.after: "fig.cap"
    fig.align: "center"
    message: false
    warning: false
    R.options:
      np.messages: false
      plot.par.mfrow: false
---

```{r libraries}
#| include: false
library(np)
library(crs)
library(car)
library(KernSmooth)
library(latex2exp)
library(MASS)
library(lmtest)
options(crs.messages=FALSE,np.messages=FALSE,np.tree=TRUE)
```

# Slide Pro-Tips {.smaller}

::: {.nonincremental}

- Link to slides - <a href="https://jeffreyracine.github.io/UPslides">jeffreyracine.github.io/UPworkshop</a> (case sensitive) (<a href="https://jeffreyracine-github-io.translate.goog/UPslides/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp#/title-slide">Google Translate</a>)

- View **full screen** by pressing the F key (press the Esc key to revert)

- Access **navigation menu** by pressing the M key (navigation menu X to close)

- **Advance** using arrow keys

- **Zoom** in by holding down the Alt key in Windows, Opt key in macOS or Ctrl key in Linux, and clicking on any screen element (Alt/Opt/Ctrl click again to zoom out)

- Use **copy to clipboard** button for R code blocks (upper right in block) to copy and paste into R/RStudio

- **Export to a PDF** by pressing the E key (wait a few seconds, then print [or print using system dialog], enable landscape layout, then save as PDF - press the E key to revert)

- Enable drawing tools - chalk **board** by pressing the B key (B to revert), notes **canvas** by pressing the C key (C to revert), press the Del key to erase, press the D key to **download drawings**

:::

::: {.notes}
Encourage participants to print/save a PDF copy of the slides as there is no guarantee that this material will be there when they realize it might be useful.
:::

{{< include density_probability.qmd >}}

{{< include regression.qmd >}}

{{< include ar_volatility_panel.qmd >}}

{{< include semipar.qmd >}}

{{< include quarto.qmd >}}

# References (scrollable)
